/** Hierarki wilayah Aceh: Kabupaten/Kota → Kecamatan → Kelurahan/Desa */

export type WilayahData = {
  [kabupaten: string]: {
    [kecamatan: string]: string[]
  }
}

export const WILAYAH_ACEH: WilayahData = {
  "Banda Aceh": {
    Baiturrahman: ["Ateuk Jawo", "Ateuk Munjeng", "Ateuk Pahlawan", "Ateuk Deah Tanoh", "Neusu Aceh", "Neusu Jaya", "Peuniti", "Seutui"],
    "Banda Raya": ["Lam Ara", "Lampulo", "Lamteumen Barat", "Lamteumen Timur", "Mulia", "Peunyerat", "Surien"],
    "Jaya Baru": ["Emperom", "Geuce Kayee Jato", "Geuce Komplek", "Punge Blang Cut", "Punge Jurong", "Punge Ulee Titi", "Ulee Pata"],
    "Kuta Alam": ["Bandar Baru", "Beurawe", "Kuta Alam", "Laksana", "Lampineung", "Peunayong", "Polisi", "Kota Baru"],
    "Kuta Raja": ["Gampong Jawa", "Gampong Mulia", "Keudah", "Merduati", "Peulanggahan", "Sukaramai"],
    "Lueng Bata": ["Batoh", "Biluy", "Lam Dom", "Lueng Bata", "Panteriek", "Peurada", "Sukadamai"],
    Meuraxa: ["Alue Deah Tengoh", "Asoe Nanggroe", "Deah Baro", "Gampong Baro", "Gampong Pie", "Lambung", "Lamjabat", "Lampaseh Aceh", "Surien"],
    "Syiah Kuala": ["Alue Naga", "Deah Raya", "Jeulingke", "Kopelma Darussalam", "Lamgugob", "Pineung", "Rukoh", "Tibang"],
    "Ulee Kareng": ["Ceurih", "Doy", "Ie Masen Kayee Adang", "Ie Masen Ulee Kareng", "Lamglumpang", "Lamjamee", "Pango Deah", "Pango Raya"],
  },
  "Sabang": {
    "Sukajaya": ["Aneuk Laot", "Balohan", "Batee Shok", "Ie Meulee", "Jaboi", "Keunekai", "Paya Seunara", "Suka Jaya"],
    "Sukakarya": ["Cot Abeuk", "Cot Ba'u", "Iboih", "Krueng Raya", "Ujong Kareung"],
  },
  "Langsa": {
    "Langsa Barat": ["Alue Beurawe", "Geudubang Aceh", "Geudubang Jawa", "Meurandeh", "Paya Bujok Beuramoe", "Paya Bujok Teungoh", "Sungai Pauh"],
    "Langsa Baro": ["Alue Dua", "Alue Dua Bakaran Bate", "Alue Merbau", "Baroh Langsa Lama", "Birem Puntong", "Langsa Lama"],
    "Langsa Kota": ["Gampong Blang", "Gampong Jawa", "Gampong Teungoh", "Gampong Tengah", "Jawa Tengah", "Matang Seulimeng", "Peukan Langsa", "Timbang Langsa"],
    "Langsa Lama": ["Alue Bilie", "Birem Bayeun", "Kapa", "Meurandeh Aceh", "Meurandeh Dayah", "Sidodadi", "Suka Jadi"],
    "Langsa Timur": ["Aja Baru", "Buket Rata", "Karang Anyar", "Paya Bujok Seuleumak", "Paya Bujok Tunong", "Sungai Lueng"],
  },
  "Lhokseumawe": {
    "Banda Sakti": ["Banda Masen", "Batuphat Barat", "Batuphat Timur", "Hagu Barat Laut", "Hagu Selatan", "Hagu Teungoh", "Keude Aceh", "Mon Geudong", "Simpang Empat"],
    "Blang Mangat": ["Cunda", "Jambo Timu", "Meunasah Mesjid", "Pusong Baru", "Pusong Lama", "Uteun Bayi"],
    "Muara Dua": ["Alue Awe", "Medang", "Mon Alue", "Paloh", "Paya Punteut", "Tumpok Teungoh"],
    "Muara Satu": ["Buket Rata", "Keude Cunda", "Meunasah Blang", "Meunasah Mee", "Meunasah Nibong", "Mon Naga"],
  },
  "Subulussalam": {
    "Penanggalan": ["Dasan", "Jontor", "Pasar Panjang", "Pegayo", "Penanggalan", "Suka Jadi"],
    "Rundeng": ["Darul Makmur", "Kuta Tinggi", "Lae Simolap", "Mandilam", "Sikelang", "Sultan Daulat"],
    "Simpang Kiri": ["Belegen Mulia", "Darul Ihsan", "Mukti Makmur", "Sepadan", "Singgersing", "Subulussalam"],
    "Longkip": ["Bawan", "Dah", "Longkip", "Namo Buaya", "Pulo Gadung"],
    "Sultan Daulat": ["Darul Aman", "Gunung Bakti", "Gunung Meriah", "Mukti Utama", "Sekelang", "Suka Maju"],
  },
  "Aceh Besar": {
    "Baitussalam": ["Cadek", "Cot Lamkuweh", "Kajhu", "Lamblang Manyang", "Lampanah Tunong", "Meunasah Kulam", "Miruk Lamreudeup"],
    "Darul Imarah": ["Lamreung", "Lambhuk", "Lam Ura", "Meunasah Manyang", "Meunasah Tutong", "Gue Gajah"],
    "Ingin Jaya": ["Lamlhom", "Lambaro", "Lam Ujong", "Mibo", "Siron", "Ulee Lheue"],
    "Kuta Baro": ["Baet", "Jantho Baru", "Meunasah Kulam", "Pagar Air", "Ulee Kareng"],
    "Lembah Seulawah": ["Awe Geutah", "Lembah Seulawah", "Meunasah Raya", "Pulo Reudeup"],
    "Mesjid Raya": ["Durung", "Meunasah Keude", "Meunasah Rayeuk", "Pulo Nasi", "Ruyung"],
    "Peukan Bada": ["Lamnga", "Meunasah Bak Trieng", "Meunasah Lambaro", "Meunasah Ule"],
    "Simpang Tiga": ["Cot Lamme", "Lam Awe", "Lampisang", "Meunasah Papeun", "Reuhat Tuha"],
    "Sukamakmur": ["Empe Tanoh", "Gampong Baro", "Krueng Lhok", "Lampeng", "Seuneubok"],
  },
  "Pidie": {
    "Kota Sigli": ["Gampong Asan", "Gampong Baro", "Gampong Blang", "Gampong Jawa", "Gampong Pisang", "Gampong Teungah", "Keramat"],
    "Mutiara": ["Gampong Mutia", "Jeumpa", "Perlak", "Raya", "Sagoe"],
    "Pidie": ["Beungga", "Dayah Baro", "Garot", "Mesjid", "Meulaboh"],
    "Delima": ["Alue Bili Rayeuk", "Cot Keh", "Delima", "Mee Peuduek", "Teupin Raya"],
    "Grong-Grong": ["Grong-Grong", "Keude Lhang", "Mesjid Kumbang", "Rikim"],
    "Indrajaya": ["Alue Naga", "Geulanggang", "Keude Jeunieb", "Meunasah Kulam", "Ruyung"],
    "Sakti": ["Ara Bungong", "Cot Trieng", "Dayah Timu", "Krueng Dheen", "Mns Sagoe"],
    "Tiro/Truseb": ["Gampong Teungah", "Kumbang", "Tiro", "Trieng Gadeng"],
  },
  "Pidie Jaya": {
    "Bandar Baru": ["Alue Papeun", "Blang Cut", "Blang Jreum", "Cot Mee", "Cot Rheu", "Keude Seumali", "Lhok Sandeng"],
    "Jangka Buya": ["Alue Dua", "Dayah Mamplam", "Jangka Buya", "Keude Jangka Buya", "Meunasah Trieng"],
    "Meurah Dua": ["Alue Pangkat", "Blang Rheum", "Cot Geundreut", "Keude Ulim", "Meunasah Baro"],
    "Meureudu": ["Cot Kuta", "Gampong Blang", "Grong-Grong", "Meureudu", "Teupin Bungong"],
    "Pante Raja": ["Blang Dalam", "Lancang", "Meunasah Kulam", "Pante Raja"],
    "Trienggadeng": ["Dayah Yub", "Ie Leubeu", "Meunasah Blang", "Meunasah Cut", "Trieng Gadeng"],
    "Ulim": ["Alue Pecalon", "Drien Tujoh", "Keutapang", "Leuhan", "Ulim"],
  },
  "Bireuen": {
    "Bireuen": ["Cot Bada", "Gegarang", "Geurugok", "Juli", "Keude Bireuen", "Meunasah Tambo Atas", "Mon Malem", "Pulo Ara", "Tanjong"],
    "Juli": ["Alue Bu Antara", "Alue Bie", "Alue Kuta", "Blang Dalam", "Cot Ane", "Juli"],
    "Kota Juang": ["Blang", "Cot Gapu", "Gampong Cot", "Gampong Teungah", "Geuleumpang Minyeuk"],
    "Kuala": ["Arongan", "Blang Mane", "Grong-Grong", "Ie Rhop", "Kuala"],
    "Makmur": ["Cot Mambong", "Geulanggang Kulam", "Lancok", "Meunasah Selasih", "Teupok Tunong"],
    "Peusangan": ["Beureugang", "Cot Puuk", "Krueng Batee", "Matang Glumpang Dua", "Peusangan"],
    "Samalanga": ["Cot Bada", "Cot Sikapal", "Geundreut", "Mns Tanjong", "Samalanga"],
  },
  "Aceh Utara": {
    "Baktiya": ["Alue Bata", "Alue Ie Mirah", "Alue Raya", "Baktiya", "Darussalam"],
    "Dewantara": ["Keude Krueng Geukueh", "Krueng Geukueh", "Meunasah Rayeuk", "Mon Geudong", "Paloh"],
    "Kuta Makmur": ["Cot Mee", "Cot Seutui", "Keude Tanoh Mirah", "Kuta Makmur", "Mns Panjo"],
    "Lhoksukon": ["Keude Lhoksukon", "Manyak Payet", "Meunasah Mesjid", "Mon Aree", "Tambon Baroh"],
    "Muara Batu": ["Darat", "Keude Muara Batu", "Kuala Batu", "Lancang Garam", "Meuraksa"],
    "Nisam": ["Batu Dua", "Lhok Beuringen", "Mns Lapang", "Nisam", "Pinto Angen"],
    "Sawang": ["Abeuk Tujoeh", "Blang Ado", "Cot Ba'u", "Keude Sawang", "Sawang"],
  },
  "Aceh Timur": {
    "Birem Bayeun": ["Alue Tho", "Bayeun", "Birem Bayeun", "Paya Bili", "Tualang"],
    "Darul Aman": ["Cot Keueung", "Darul Aman", "Jambo Lubok", "Karang Baru", "Reuleut"],
    "Idi Rayeuk": ["Banda Alam", "Gampong Teurebe", "Idi Cut", "Idi Rayeuk", "Keude Idi"],
    "Julok": ["Alue Sikaya", "Bale Redelong", "Julok", "Paya Demam", "Pulo Blang"],
    "Madat": ["Alee Gampong", "Alue Ie Mirah", "Cot Darat", "Madat", "Siren"],
    "Nurussalam": ["Bugak Krueng", "Cot Naleung", "Kuta Binje", "Lhok Nibong", "Nurussalam"],
    "Peureulak": ["Alue Mangki", "Bentayan", "Cek Mbon", "Peureulak", "Seunudon"],
  },
  "Aceh Tamiang": {
    "Banda Mulia": ["Alur Baning", "Alur Bemban", "Alur Manis", "Alur Naga", "Alur Pinang"],
    "Bendahara": ["Alur Akar", "Bendahara", "Kuala Simpang", "Paya Rahat", "Teluk Kemang"],
    "Karang Baru": ["Bukit Tempurung", "Darul Aman", "Karang Baru", "Paya Kulbi", "Tanjung Keramat"],
    "Kejuruan Muda": ["Bukit Rata", "Kampung Belakang", "Kota Panjang", "Paya Tampah", "Tanjong Karang"],
    "Kota Kuala Simpang": ["Benua Raja", "Kebun Aron", "Kesehatan", "Kota Kuala Simpang", "Pekan Satu"],
    "Manyak Payed": ["Alur Mas", "Alur Selalas", "Bineh Krueng", "Manyak Payed", "Paya Rahat"],
    "Rantau": ["Rantau", "Seruway", "Tualang", "Upah", "Bandar Setia"],
  },
  "Aceh Tengah": {
    "Bebesen": ["Bebesen", "Blang Gele", "Empus", "Kenawat", "Kemala Muda", "Kute Kering", "Paya Tumpi Baru", "Paya Tumpi Lama", "Tawar"],
    "Bintang": ["Atu Gajah", "Bintang", "Celala", "Despot", "Wih Nara"],
    "Kebayakan": ["Bebesen", "Blang Kolak I", "Blang Kolak II", "Bukit", "Hakim Bale", "Kebayakan", "Lot Bener"],
    "Ketol": ["Buter", "Gemboyah", "Ketol", "Kute Gayo", "Kute Lot", "Rime Raya", "Simpang Kelaping"],
    "Kute Panang": ["Bale Redelong", "Blang Bintang", "Kute Panang", "Mongal", "Tawar Sedenge"],
    "Linge": ["Angkup", "Babussalam", "Bale", "Ise-Ise", "Linge", "Penosan"],
    "Silih Nara": ["Dedamar", "Gegarang", "Hakim Bale", "Pakat Jeroh", "Silih Nara"],
  },
  "Gayo Lues": {
    "Blangkejeren": ["Ature", "Blangkejeren", "Kalang", "Kota", "Penosan", "Rikit Gaib", "Rikit Musara"],
    "Blang Pegayon": ["Bencah", "Jagong", "Kenyaran", "Penampaan Uken", "Rerebe"],
    "Dabun Gelanggang": ["Agusen", "Dabun Gelanggang", "Lesten", "Pepayungen", "Singah Mulo"],
    "Pining": ["Bidin", "Cane Uken", "Pining", "Toweren", "Wih Pesam"],
    "Putri Betung": ["Ayer Dikit", "Kandang", "Lawe Sumur", "Putri Betung", "Rerebe"],
    "Rikit Gaib": ["Buntul Kemumu", "Gumpang", "Penampaan", "Puteri Betung", "Rikit Gaib"],
    "Terangun": ["Gele", "Kampung Baru", "Leme", "Rerebe", "Terangun"],
    "Tripe Jaya": ["Agusen", "Bener Lukup", "Pasir Putih", "Penampaan", "Tripe"],
  },
  "Aceh Tenggara": {
    "Babussalam": ["Alur Gading", "Babussalam", "Bamil Baru", "Kuta Cane", "Lak-Lak", "Peristiwa"],
    "Badar": ["Bambel", "Gumpang Jering", "Jongar", "Kuta Cane", "Lawe Mamas"],
    "Bambel": ["Bandar Jaya", "Bambel", "Gumpang Jering", "Lawe Perbuatan", "Lawe Sumur"],
    "Bukit Tusam": ["Alur Baning", "Lawe Alas", "Lawe Dua", "Lawe Hulu", "Lawe Sumur"],
    "Ketambe": ["Arul Cicah", "Hamping Prida", "Ketambe", "Lawe Gurung", "Tualang"],
    "Lawe Alas": ["Atan Kuala", "Cipare-Pare", "Kuta Pengkih", "Lawe Alas", "Lawe Sumur"],
    "Lawe Bulan": ["Alur Cucur", "Aud Lah", "Lawe Bulan", "Lawe Sumur", "Tanjung Slamat"],
    "Semadam": ["Keliling Gunung", "Lawe Semadam", "Semadam", "Sepakat", "Sitale"],
  },
  "Aceh Selatan": {
    "Bakongan": ["Bakongan", "Drien Jalo", "Ie Alang", "Keude Bakongan", "Pisang Baru"],
    "Kluet Selatan": ["Kluet Selatan", "Makmur Mulia", "Meukek", "Pulo Kambing", "Suaq Bakong"],
    "Kluet Tengah": ["Alur Hitam", "Durian Kawan", "Kluet Tengah", "Menggamat", "Paya"],
    "Kluet Timur": ["Alur Batu", "Kluet Timur", "Lawe Sawah", "Mersak", "Tenggulun"],
    "Kluet Utara": ["Batumbuang", "Kampung Paya", "Kluet Utara", "Paya Laba", "Siurai-Urai"],
    "Labuhanhaji": ["Drien Jalo", "Labuhanhaji", "Lhok Pawoh", "Sawang", "Ujung Karang"],
    "Meukek": ["Alur Seunong", "Gunung Rotan", "Kedai Baro", "Kute Baro", "Lhok Bengkuang"],
    "Tapaktuan": ["Air Berudang", "Barak Aceh", "Hilir", "Hulu", "Lhok Bengkuang", "Padang", "Pandan", "Tapaktuan"],
  },
  "Aceh Barat Daya": {
    "Babahrot": ["Alue Rambot", "Babahrot", "Cot Seulamat", "Gunung Samarinda", "Paya Laba"],
    "Blangpidie": ["Beureugang", "Blangpidie", "Cot Lada", "Gampong Baro", "Gampong Baru"],
    "Jeumpa": ["Drien Rampak", "Gunung Cut", "Jeumpa", "Kuta Baro", "Lhung Panjang"],
    "Kuala Batee": ["Alue Raya", "Kuta Baro", "Kuala Batee", "Pasi Mali", "Paya Bila"],
    "Lembah Sabil": ["Alur Seumantok", "Lembah Sabil", "Meukek", "Pante Ara", "Paya Baro"],
    "Manggeng": ["Alue Papeun", "Keude Manggeng", "Manggeng", "Meudang Ara", "Padang Meurante"],
    "Setia": ["Cot Plieng", "Kuta Baro", "Padang", "Sawang", "Setia"],
    "Susoh": ["Blang Baro", "Kesehatan", "Padang", "Pasar", "Susoh"],
  },
  "Aceh Barat": {
    "Arongan Lambalek": ["Alue Bata", "Arongan", "Blang Dalam", "Cot Mee", "Ie Mameh"],
    "Bubon": ["Alue Batee", "Bubon", "Cot Kuta", "Cot Seulamat", "Suak Raya"],
    "Johan Pahlawan": ["Drien Rampak", "Gampong Baro", "Gampoeng Teungoh", "Johan Pahlawan", "Kampung Belakang", "Lapang", "Meulaboh", "Padang Seurahet"],
    "Kaway XVI": ["Alue Peuya", "Cot Pluh", "Cot Raya", "Cot Seulamat", "Kaway XVI"],
    "Meureubo": ["Alue Raya", "Cot Seulamat", "Meureubo", "Peunaga Cut Ujong", "Ujong Fatihah"],
    "Pante Ceureumen": ["Blang Dalam", "Keumala Indah", "Pante Ceureumen", "Paya Leu", "Ranto Panyang"],
    "Samatiga": ["Alue Bata", "Cot Rambong", "Drien Rampak", "Samatiga", "Tanjung"],
    "Woyla": ["Blang Pidie", "Cot Seumantok", "Kuala Bhee", "Manggeng", "Woyla"],
  },
  "Nagan Raya": {
    "Beutong": ["Alue Bata", "Beutong", "Blang Jreum", "Cot Kuta", "Paya Rambong"],
    "Beutong Ateuh Banggalang": ["Beutong Ateuh", "Blang Pohroh", "Kuta Tuha", "Pameu", "Sapek"],
    "Darul Makmur": ["Alue Ue", "Cot Rambong", "Darul Makmur", "Kota Fajar", "Kuala Trang"],
    "Kuala": ["Cot Ba'u", "Kuala", "Lubok Batee", "Padang", "Suak Puntong"],
    "Kuala Pesisir": ["Alue Bata", "Blang Baro", "Cot Rheu", "Kuala Pesisir", "Meureubo"],
    "Seunagan": ["Alue Tho", "Cot Kuta", "Jeuram", "Meupisang", "Seunagan"],
    "Seunagan Timur": ["Baro", "Blang Kuta", "Kota Raya", "Meupisang", "Seunagan Timur"],
    "Suka Makmue": ["Cot Rambong", "Drien Rampak", "Krueng Ceuko", "Pante Geulima", "Suka Makmue"],
    "Tadu Raya": ["Blang Mancung", "Cot Bek", "Kuta Trieng", "Leupung", "Tadu Raya"],
  },
  "Simeulue": {
    "Alafan": ["Aie Batu", "Alafan", "Kuala Makmur", "Lafakha", "Malasin"],
    "Salang": ["Layabaung", "Luan Balu", "Salang", "Simeulucut", "Teupah Selatan"],
    "Simeulue Barat": ["Batu Berlayar", "Latiung", "Sanggiran", "Simeulue Barat", "Sinabang"],
    "Simeulue Cut": ["Jambu Air", "Lalang", "Lewak", "Maudil", "Simeulue Cut"],
    "Simeulue Timur": ["Amaiteng Mulia", "Amanatun", "Ameria Bahagia", "Amilan", "Sinabang", "Suka Maju"],
    "Teupah Barat": ["Babul Makmur", "Matanuruk", "Salur", "Serafon", "Teupah Barat"],
    "Teupah Selatan": ["Kebun Baru", "Latiung", "Malasin", "Mutiara", "Teupah Selatan"],
    "Teluk Dalam": ["Batu Ragi", "Kabul", "Latiung", "Malasin", "Teluk Dalam"],
  },
  "Aceh Singkil": {
    "Danau Paris": ["Bintang Marasi", "Danau Paris", "Lae Mate", "Lae Sipan", "Lipat Kajang"],
    "Gunung Meriah": ["Batu Mbelin", "Gunung Meriah", "Kinali", "Lae Butar", "Lae Sipan"],
    "Kota Baharu": ["Kota Baharu", "Lae Besi", "Rantau", "Sabang Musam", "Sianjo-Anjo"],
    "Kuala Baru": ["Batu Ampar", "Kuala Baru", "Lae Butar", "Pulau Sarok", "Tanjung Mas"],
    "Pulau Banyak": ["Haloban", "Pulau Baguk", "Pulau Banyak Barat", "Pulau Tailana", "Ujung Sialit"],
    "Singkil": ["Batu Rundang", "Kota Singkil", "Rantau Gedang", "Singkil", "Singkil Utara"],
    "Singkil Utara": ["Alur Baung", "Lae Batu", "Lae Riman", "Singkil Utara", "Ujung Bawang"],
    "Simpang Kanan": ["Binanga", "Lawe Bangun", "Lawe Penanggalan", "Lowe Mamas", "Simpang Kanan"],
    "Suro": ["Danau Gelinggang", "Lae Sipan", "Siatas", "Suro", "Suro Baru"],
  },
  "Bener Meriah": {
    "Bandar": ["Blang Sentang", "Buntul Kemumu", "Ise-Ise", "Kala Kemili", "Rampak Barat"],
    "Bener Kelipah": ["Bener Kelipah Selatan", "Bener Kelipah Utara", "Belang Bebangka", "Bujang", "Kute Pertanak"],
    "Bukit": ["Atu Tulu", "Bebini", "Blang Kucak", "Jelobok", "Kute Kering"],
    "Gajah Putih": ["Gajah Putih", "Kute Tanyung", "Meluem", "Paya Ringkel", "Ronga-Ronga"],
    "Mesidah": ["Gegur Sepakat", "Hakim Bale", "Kute Lintang", "Mesidah", "Simpang Renggali"],
    "Permata": ["Bale Redelong", "Gemasih", "Kenawat Redelong", "Permata", "Uring"],
    "Pintu Rime Gayo": ["Berkubu", "Blow Jaya", "Cemparam Baru", "Pintu Rime", "Weh Porak"],
    "Syiah Utama": ["Blang Ara", "Buntul Gayo", "Isaq", "Seri Delima", "Syiah Utama"],
    "Timang Gajah": ["Bener Mulie", "Blang Ara", "Gegur Musara", "Karang Rejo", "Timang Gajah"],
    "Wih Pesam": ["Bebesen", "Blang Benara", "Blang Jorong", "Simpang Tiga Redelong", "Wih Pesam"],
  },
  "Aceh Jaya": {
    "Darul Hikmah": ["Babah Dua", "Breueh Lheu", "Cot Seulamat", "Darul Hikmah", "Paya Baro"],
    "Indra Jaya": ["Cot Kuthang", "Indra Jaya", "Masen Indra Jaya", "Mon Bateung", "Panga"],
    "Jaya": ["Beutong", "Jaya", "Keude Unga", "Meunasah Kulam", "Mon Bateung"],
    "Krueng Sabee": ["Calang", "Cot Punti", "Keude Krueng Sabee", "Krueng Sabee", "Layeun"],
    "Lhok Kruet": ["Babah Nipah", "Lhok Bubon", "Lhok Kruet", "Lhok Timon", "Rigaih"],
    "Panga": ["Alue Baro", "Blang Pidie", "Panga", "Panga Barat", "Tuwi Kareung"],
    "Pasie Raya": ["Alue Raya", "Geulumpang", "Kepala Bandar", "Pasie Raya", "Peunia"],
    "Setia Bakti": ["Datar", "Keude Teunom", "Muara Teunom", "Setia Bakti", "Teunom"],
    "Sampoiniet": ["Babah Leh", "Keutapang Mameh", "Krueng Sabee", "Peulanteu", "Sampoiniet"],
    "Teunom": ["Cot Punti", "Gunong Tarok", "Keude Teunom", "Lhok Pange", "Teunom"],
  },
}

export const KAB_KOTA_ACEH = Object.keys(WILAYAH_ACEH).sort()

export function getKecamatanList(kabupaten: string): string[] {
  if (!kabupaten || !WILAYAH_ACEH[kabupaten]) return []
  return Object.keys(WILAYAH_ACEH[kabupaten]).sort()
}

export function getKelurahanList(kabupaten: string, kecamatan: string): string[] {
  if (!kabupaten || !kecamatan) return []
  return WILAYAH_ACEH[kabupaten]?.[kecamatan] ?? []
}
